name: web3dart
description: Dart library to connect to Ethereum clients. Send transactions and interact with smart contracts!
version: 2.7.3-gate+3
homepage: https://pwa.ir
repository: https://github.com/xclud/web3dart

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  pointycastle: ^3.7.4
  sec: ^1.1.0
  http: ">=0.13.1 <2.0.0"
  uuid: ^4.0.0
  json_rpc_2: ^3.0.2
  stream_transform: ^2.1.0
  stream_channel: ^2.1.2
  eip55: ^1.0.2
  eip1559: ^0.6.2
  typed_data: ^1.3.2
  convert: ^3.1.1
  async: ^2.11.0
  wallet: ^0.0.13
  web_socket_channel: ^2.4.0

dev_dependencies:
  test: ^1.24.6
  lints: ^3.0.0
  # # Gate命令工具库
  gate_cli:
    version: ^2.16.6
    hosted: https://app-ci-portal.gatexsecurity.com
